# Import Dependencies

In [1]:
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os

C:\Users\alama\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\alama\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


# Testing environment

In [1]:
# !python -m atari_py.import_roms ./Roms/ROMS

copying adventure.bin from ./Roms/ROMS\Adventure (1980) (Atari, Warren Robinett) (CX2613, CX2613P) (PAL).bin to C:\Users\alama\anaconda3\lib\site-packages\atari_py\atari_roms\adventure.bin
copying air_raid.bin from ./Roms/ROMS\Air Raid (1982) (Men-A-Vision) (PAL) ~.bin to C:\Users\alama\anaconda3\lib\site-packages\atari_py\atari_roms\air_raid.bin
copying alien.bin from ./Roms/ROMS\Alien (1982) (20th Century Fox Video Games, Douglas 'Dallas North' Neubauer) (11006) ~.bin to C:\Users\alama\anaconda3\lib\site-packages\atari_py\atari_roms\alien.bin
copying amidar.bin from ./Roms/ROMS\Amidar (1982) (Parker Brothers, Ed Temple) (PB5310) ~.bin to C:\Users\alama\anaconda3\lib\site-packages\atari_py\atari_roms\amidar.bin
copying assault.bin from ./Roms/ROMS\Assault (AKA Sky Alien) (1983) (Bomb - Onbase) (CA281).bin to C:\Users\alama\anaconda3\lib\site-packages\atari_py\atari_roms\assault.bin
copying asterix.bin from ./Roms/ROMS\Asterix (AKA Taz) (1984) (Atari, Jerome Domurat, Steve Woita) (CX26

In [2]:
environment_name = 'Breakout-v4'
env = gym.make(environment_name,render_mode = 'rgb_array')

In [3]:
env.reset()

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 {'lives': 5, 'episode_frame_number': 0, 'frame_number': 0})

In [4]:
env.action_space.sample()

1

In [5]:
env.observation_space

Box(0, 255, (210, 160, 3), uint8)

In [6]:
episodes = 5
for episode in range(1,episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        obs, reward, done,truncated, info = env.step(action)
        done = done | truncated
        score += reward
    print(f'Episode: {episode} Score: {score}')
env.close()

C:\Users\alama\anaconda3\lib\site-packages\gym\utils\passive_env_checker.py:289: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(
C:\Users\alama\anaconda3\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Episode: 1 Score: 0.0
Episode: 2 Score: 0.0
Episode: 3 Score: 1.0
Episode: 4 Score: 3.0
Episode: 5 Score: 0.0


In [7]:
action = env.action_space.sample()

In [23]:
env.step(action)

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 0.0,
 False,
 False,
 {'lives': 5, 'episode_frame_number': 4, 'frame_number': 4})

# Vectorise Environment and Train Model

In [12]:
env = make_atari_env('Breakout-v4',n_envs = 4,seed=0)
env = VecFrameStack(env, n_stack = 4)

In [14]:
env.reset()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [16]:
env.close()

In [17]:
log_path = os.path.join('Training','Logs')
model = A2C('CnnPolicy', env, verbose = 1,tensorboard_log = log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


Our model is taking it's output in the form of images in 3 channels rgb hence instead of mlp we use cnn

In [18]:
model.learn(total_timesteps = 100000)

Logging to Training\Logs\A2C_1
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 272      |
|    ep_rew_mean        | 1.51     |
| time/                 |          |
|    fps                | 169      |
|    iterations         | 100      |
|    time_elapsed       | 11       |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -1.37    |
|    explained_variance | 0.0692   |
|    learning_rate      | 0.0007   |
|    n_updates          | 99       |
|    policy_loss        | -0.326   |
|    value_loss         | 0.0964   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 283      |
|    ep_rew_mean        | 1.63     |
| time/                 |          |
|    fps                | 165      |
|    iterations         | 200      |
|    time_elapsed       | 24       |
|    total_timesteps    | 4000     |
| train

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 314      |
|    ep_rew_mean        | 2.46     |
| time/                 |          |
|    fps                | 155      |
|    iterations         | 1400     |
|    time_elapsed       | 180      |
|    total_timesteps    | 28000    |
| train/                |          |
|    entropy_loss       | -0.538   |
|    explained_variance | -0.547   |
|    learning_rate      | 0.0007   |
|    n_updates          | 1399     |
|    policy_loss        | 0.0388   |
|    value_loss         | 0.00632  |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 284      |
|    ep_rew_mean        | 1.96     |
| time/                 |          |
|    fps                | 154      |
|    iterations         | 1500     |
|    time_elapsed       | 193      |
|    total_timesteps    | 30000    |
| train/                |          |
|

------------------------------------
| rollout/              |          |
|    ep_len_mean        | 442      |
|    ep_rew_mean        | 5.05     |
| time/                 |          |
|    fps                | 157      |
|    iterations         | 2800     |
|    time_elapsed       | 356      |
|    total_timesteps    | 56000    |
| train/                |          |
|    entropy_loss       | -0.183   |
|    explained_variance | 0.973    |
|    learning_rate      | 0.0007   |
|    n_updates          | 2799     |
|    policy_loss        | 0.00616  |
|    value_loss         | 0.0148   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 449      |
|    ep_rew_mean        | 5.23     |
| time/                 |          |
|    fps                | 157      |
|    iterations         | 2900     |
|    time_elapsed       | 367      |
|    total_timesteps    | 58000    |
| train/                |          |
|

-------------------------------------
| rollout/              |           |
|    ep_len_mean        | 480       |
|    ep_rew_mean        | 5.81      |
| time/                 |           |
|    fps                | 161       |
|    iterations         | 4200      |
|    time_elapsed       | 520       |
|    total_timesteps    | 84000     |
| train/                |           |
|    entropy_loss       | -0.0541   |
|    explained_variance | 0.968     |
|    learning_rate      | 0.0007    |
|    n_updates          | 4199      |
|    policy_loss        | -4.92e-05 |
|    value_loss         | 0.0282    |
-------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 486      |
|    ep_rew_mean        | 5.95     |
| time/                 |          |
|    fps                | 161      |
|    iterations         | 4300     |
|    time_elapsed       | 531      |
|    total_timesteps    | 86000    |
| train/             

In [21]:
a2c_path = os.path.join('Training','Saved Models','A2C_Breakout_Model')
model.save(a2c_path)

In [22]:
del model

In [23]:
model = A2C.load(a2c_path,env)

Wrapping the env in a VecTransposeImage.


# Evaluate and Test

In [26]:
env = make_atari_env('Breakout-v4',n_envs = 1,seed = 0)
env = VecFrameStack(env,n_stack = 4)

In [27]:
evaluate_policy(model,env,n_eval_episodes=10,render=True)

C:\Users\alama\anaconda3\lib\site-packages\gymnasium\utils\passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


(8.0, 2.32379000772445)

In [28]:
env.close()